---
################
#################
- hosts: servidor
  tasks:

  - name: Copiando o diretorio do projeto
    copy:
      src: minio_uploader
      dest: /tmp/
 
  - name: Atualizando pacotes
    apt: 
      update_cache: yes
 
  - name: Install a list of packages
    apt:
      pkg:
      - python3
      - python3-pip
      - expect

  - name: install pipenv
    shell: pip3 install pipenv 

  - name: deploy
    shell: pipenv --python 3 install --system --deploy 
    args:
      chdir: /tmp/minio_uploader/

  - name: Setting environment variables
    shell: | 
      echo 'export S3_URL=http://play.min.io' >> /root/.bashrc
      echo 'export S3_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F' >> /root/.bashrc
      echo 'export S3_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG' >> /root/.bashrc

  - name: Copiando script gunicorn para o servidor remoto
    copy:
      src: gunicorn.sh
      dest: /tmp/
      mode: 0755
  
  - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
    shell: . gunicorn.sh {{ansible_user}} {{ansible_ssh_pass}}
    args:
      chdir: /tmp/
      executable: /bin/bash

  - name: Copiando imagem para o servidor remoto
    copy:
      src: ansible.png
      dest: /tmp


  - name: Executar o curl 
    shell: curl -X POST -F "file=@/tmp/ansible.png" http://{{ansible_host}}:5000/minio-upload/instruct-silas/ansible.png


